// Licensed to Elasticsearch B.V under one or more agreements.
// Elasticsearch B.V licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information

/*
IMPORTANT NOTE
==============
This file has been generated.
If you wish to submit a PR please modify the original csharp file and submit the PR with that change. Thanks!
*/

using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace Elastic.CommonSchema
{
	/// <summary>
	/// Bidirectional mapping tables between ECS field paths and OTel semantic convention attribute names.
	/// Only includes <c>match</c> and <c>equivalent</c> relations.
	/// </summary>
	public static class OTelMappings
	{
		/// <summary>
		/// ECS field path to OTel attribute name(s) for fields where the names differ (equivalent relation).
		/// For match relations the names are identical and not listed here.
		/// </summary>
		public static readonly IReadOnlyDictionary<string, string[]> EcsToOTel =
			new ReadOnlyDictionary<string, string[]>(new Dictionary<string, string[]>
			{
				{ "cloud.service.name", new[] { "cloud.platform" } },
				{ "container.image.hash.all", new[] { "container.image.repo_digests" } },
				{ "container.image.tag", new[] { "container.image.tags" } },
				{ "container.runtime", new[] { "container.runtime.name" } },
				{ "error.message", new[] { "exception.message" } },
				{ "error.stack_trace", new[] { "exception.stacktrace" } },
				{ "faas.execution", new[] { "faas.invocation_id" } },
				{ "faas.trigger.type", new[] { "faas.trigger" } },
				{ "file.ctime", new[] { "file.changed" } },
				{ "file.gid", new[] { "file.group.id" } },
				{ "file.group", new[] { "file.group.name" } },
				{ "file.mtime", new[] { "file.modified" } },
				{ "file.owner", new[] { "file.owner.name" } },
				{ "file.target_path", new[] { "file.symbolic_link.target_path" } },
				{ "file.uid", new[] { "file.owner.id" } },
				{ "gen_ai.system", new[] { "gen_ai.provider.name" } },
				{ "geo.city_name", new[] { "geo.locality.name" } },
				{ "geo.continent_code", new[] { "geo.continent.code" } },
				{ "geo.country_iso_code", new[] { "geo.country.iso_code" } },
				{ "geo.region_iso_code", new[] { "geo.region.iso_code" } },
				{ "host.architecture", new[] { "host.arch" } },
				{ "http.request.body.bytes", new[] { "http.request.body.size" } },
				{ "http.request.bytes", new[] { "http.request.size" } },
				{ "http.request.method", new[] { "http.request.method_original" } },
				{ "http.response.body.bytes", new[] { "http.response.body.size" } },
				{ "http.response.bytes", new[] { "http.response.size" } },
				{ "network.protocol", new[] { "network.protocol.name" } },
				{ "os.full", new[] { "os.description" } },
				{ "process.args", new[] { "process.command_args" } },
				{ "process.executable", new[] { "process.executable.path" } },
				{ "service.environment", new[] { "deployment.environment.name" } },
				{ "service.node.name", new[] { "service.instance.id" } },
			});

		/// <summary>
		/// OTel attribute name to ECS field path for fields where the names differ (equivalent relation).
		/// For match relations the names are identical and not listed here.
		/// </summary>
		public static readonly IReadOnlyDictionary<string, string> OTelToEcs =
			new ReadOnlyDictionary<string, string>(new Dictionary<string, string>
			{
				{ "cloud.platform", "cloud.service.name" },
				{ "container.image.repo_digests", "container.image.hash.all" },
				{ "container.image.tags", "container.image.tag" },
				{ "container.runtime.name", "container.runtime" },
				{ "deployment.environment.name", "service.environment" },
				{ "exception.message", "error.message" },
				{ "exception.stacktrace", "error.stack_trace" },
				{ "faas.invocation_id", "faas.execution" },
				{ "faas.trigger", "faas.trigger.type" },
				{ "file.changed", "file.ctime" },
				{ "file.group.id", "file.gid" },
				{ "file.group.name", "file.group" },
				{ "file.modified", "file.mtime" },
				{ "file.owner.id", "file.uid" },
				{ "file.owner.name", "file.owner" },
				{ "file.symbolic_link.target_path", "file.target_path" },
				{ "gen_ai.provider.name", "gen_ai.system" },
				{ "geo.continent.code", "geo.continent_code" },
				{ "geo.country.iso_code", "geo.country_iso_code" },
				{ "geo.locality.name", "geo.city_name" },
				{ "geo.region.iso_code", "geo.region_iso_code" },
				{ "host.arch", "host.architecture" },
				{ "http.request.body.size", "http.request.body.bytes" },
				{ "http.request.method_original", "http.request.method" },
				{ "http.request.size", "http.request.bytes" },
				{ "http.response.body.size", "http.response.body.bytes" },
				{ "http.response.size", "http.response.bytes" },
				{ "network.protocol.name", "network.protocol" },
				{ "os.description", "os.full" },
				{ "process.command_args", "process.args" },
				{ "process.executable.path", "process.executable" },
				{ "service.instance.id", "service.node.name" },
			});

		/// <summary>
		/// All bidirectional ECS field paths (both match and equivalent).
		/// These are ECS fields that have a corresponding OTel semantic convention.
		/// </summary>
		public static readonly IReadOnlyCollection<string> AllBidirectionalEcsFields = new HashSet<string>
		{
			"client.address",
			"client.port",
			"cloud.account.id",
			"cloud.availability_zone",
			"cloud.provider",
			"cloud.region",
			"cloud.service.name",
			"container.id",
			"container.image.hash.all",
			"container.image.name",
			"container.image.tag",
			"container.name",
			"container.runtime",
			"destination.address",
			"destination.port",
			"device.id",
			"device.manufacturer",
			"device.model.identifier",
			"device.model.name",
			"dns.question.name",
			"error.message",
			"error.stack_trace",
			"error.type",
			"faas.coldstart",
			"faas.execution",
			"faas.name",
			"faas.trigger.type",
			"faas.version",
			"file.accessed",
			"file.attributes",
			"file.created",
			"file.ctime",
			"file.directory",
			"file.extension",
			"file.fork_name",
			"file.gid",
			"file.group",
			"file.inode",
			"file.mode",
			"file.mtime",
			"file.name",
			"file.owner",
			"file.path",
			"file.size",
			"file.target_path",
			"file.uid",
			"gen_ai.agent.description",
			"gen_ai.agent.id",
			"gen_ai.agent.name",
			"gen_ai.operation.name",
			"gen_ai.output.type",
			"gen_ai.request.choice.count",
			"gen_ai.request.encoding_formats",
			"gen_ai.request.frequency_penalty",
			"gen_ai.request.max_tokens",
			"gen_ai.request.model",
			"gen_ai.request.presence_penalty",
			"gen_ai.request.seed",
			"gen_ai.request.stop_sequences",
			"gen_ai.request.temperature",
			"gen_ai.request.top_k",
			"gen_ai.request.top_p",
			"gen_ai.response.finish_reasons",
			"gen_ai.response.id",
			"gen_ai.response.model",
			"gen_ai.system",
			"gen_ai.token.type",
			"gen_ai.tool.call.id",
			"gen_ai.tool.name",
			"gen_ai.tool.type",
			"gen_ai.usage.input_tokens",
			"gen_ai.usage.output_tokens",
			"geo.city_name",
			"geo.continent_code",
			"geo.country_iso_code",
			"geo.postal_code",
			"geo.region_iso_code",
			"host.architecture",
			"host.id",
			"host.ip",
			"host.mac",
			"host.name",
			"host.type",
			"http.request.body.bytes",
			"http.request.bytes",
			"http.request.method",
			"http.response.body.bytes",
			"http.response.bytes",
			"http.response.status_code",
			"log.file.path",
			"network.protocol",
			"network.transport",
			"network.type",
			"os.full",
			"os.name",
			"os.version",
			"process.args",
			"process.args_count",
			"process.command_line",
			"process.executable",
			"process.group_leader.pid",
			"process.interactive",
			"process.pid",
			"process.real_user.id",
			"process.real_user.name",
			"process.saved_user.id",
			"process.saved_user.name",
			"process.session_leader.pid",
			"process.title",
			"process.user.id",
			"process.user.name",
			"process.vpid",
			"process.working_directory",
			"server.address",
			"server.port",
			"service.environment",
			"service.name",
			"service.node.name",
			"service.version",
			"source.address",
			"source.port",
			"tls.cipher",
			"tls.client.certificate",
			"tls.client.certificate_chain",
			"tls.client.hash.md5",
			"tls.client.hash.sha1",
			"tls.client.hash.sha256",
			"tls.client.issuer",
			"tls.client.ja3",
			"tls.client.not_after",
			"tls.client.not_before",
			"tls.client.subject",
			"tls.client.supported_ciphers",
			"tls.curve",
			"tls.established",
			"tls.next_protocol",
			"tls.resumed",
			"tls.server.certificate",
			"tls.server.certificate_chain",
			"tls.server.hash.md5",
			"tls.server.hash.sha1",
			"tls.server.hash.sha256",
			"tls.server.issuer",
			"tls.server.ja3s",
			"tls.server.not_after",
			"tls.server.not_before",
			"tls.server.subject",
			"url.domain",
			"url.extension",
			"url.fragment",
			"url.full",
			"url.original",
			"url.path",
			"url.port",
			"url.query",
			"url.registered_domain",
			"url.scheme",
			"url.subdomain",
			"url.top_level_domain",
			"user_agent.name",
			"user_agent.original",
			"user_agent.version",
			"user.email",
			"user.full_name",
			"user.hash",
			"user.id",
			"user.name",
			"user.roles",
		};
	}
}
