version: 1.0.{build}
image:
    - Visual Studio 2017
test: off
environment:
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
install:
    - cmd: choco install dotnetcore-sdk --version 3.0.100
build_script:
    - cmd: build.bat canary

nuget:
    disable_publish_on_pr: true

for:

    - branches:
          only:
              - /^(master|\d+\.x)$/
      artifacts:
          - path: .\build\output\_packages\*.nupkg
            name: NuGet
