jobs:
- job: LinuxUnitTests
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: UseDotNet@2
    inputs:
        version: '3.0.100'
  - script: ./build.sh test
    displayName: 'build and unit test'
  - task: PublishTestResults@2
    inputs:
        testRunner: VSTest
        testResultsFiles: 'tests/**/*.trx'
        testRunTitle: Linux Unit Tests

- job: WindowsUnitTests
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: UseDotNet@2
    inputs:
      version: '3.0.100'
  - script: build.bat test
    displayName: 'build and unit test'
  - task: PublishTestResults@2
    inputs:
      testRunner: VSTest
      testResultsFiles: 'tests/**/*.trx'
      testRunTitle: Windows Unit Tests
