ifdef::env-github[]
NOTE: For the best reading experience,
please view this documentation at https://www.elastic.co/guide/en/ecs-logging/dotnet[elastic.co]
endif::[]

== Formatters

Our log formatters allow you to change the way various logging frameworks
log to IO (file/console) to use ECS json.

[float]
=== ECS Aware Message Templates

Our log formatters allow you to set ECS fields directly from the message template using properties that adhere to the
https://messagetemplates.org/ format.

[source,chsarp]
----
Log.Information("The time is {TraceId}", "my-trace-id");
----

Will directly override `trace.id` on the resulting ECS json document.

All supported ECS message template properties are available as constants under the `LogTemplateProperties` static class. 
For example `LogTemplateProperties.TraceId` will return `"TraceId"`.



[float]
=== Ingest ECS log files

If you are using one of our formatter libraries to log to file or stdout/stderr you can use the following options 
to get these logs into Elasticsearch or Elastic Cloud:

NOTE: We also support writing logs directly to Elasticsearch or Elastic Cloud. See our <<data-shippers, various data shipper integrations>>

include::{ecs-repo-dir}/setup.asciidoc[tag=configure-filebeat]

include::./serilog.asciidoc[Serilog]
include::./nlog.asciidoc[NLog]
include::./log4net.asciidoc[log4net]

