[[setup]]
== Get Started

[float]
[[setup-step-1]]
=== Step 1: Configure application logging

If you want to integrate with an existing logger emitting ECS json to a file or stdout/stderr.

Choose one of our formatters:

* <<serilog-formatter, `Elastic.CommonSchema.Serilog`>>
* <<nlog-formatter, `Elastic.CommonSchema.NLog`>>
* <<log4net-formatter, `Elastic.CommonSchema.Log4Net`>>

If you want to write the logs directly to one of Elastic's endpoints (e.g Elastic Cloud / Elasticsearch)  

Choose one of our data shipping loggers:

* <<serilog-data-shipper, `Elastic.Serilog.Sinks`>>
* <<extensions-logging-data-shipper, `Elastic.Extensions.Logging`>>

[float]
[[setup-step-2]]
=== Step 2: Enable APM log correlation (optional)
If you are using the Elastic APM .NET agent,
{apm-dotnet-ref}/log-correlation.html[log correlation can be configured] to
inject trace, transaction and span id fields into log events.

By default the ECS logging integrations will read tracing information from
https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.activity?view=net-7.0[System.Diagnostics.Activity]
if the APM logging corrolation libraries are not installed.

[float]
[[setup-step-3]]
=== Step 3: Configure Filebeat (optional)

If you are using one of our log formatters you can use the following methods 
to ship these logs to Elastic.

include::{ecs-repo-dir}/setup.asciidoc[tag=configure-filebeat]
