name: pre-commit

on:
  pull_request:
  push:
    branches:
      - main
      - 1.*

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: elastic/apm-pipeline-library/.github/actions/pre-commit@current